#!/bin/bash
APPDIR=/workspace
IMAGE=$(basename $0):latest
WSUSER=${WSUSER:-wario}

if [ $# = 0 ] ; then
    echo Please specify what to start
    exit 1
fi

DOCKER_PREFIX="${DOCKER_PREFIX:-fozztexx}"

if [[ "${IMAGE}" != */* ]]; then
    if ! docker inspect "${IMAGE}" >/dev/null 2>&1 ; then
        IMAGE="${DOCKER_PREFIX}/${IMAGE}"
    fi
fi

# The yocto/windriver scripts will save the working directory
# but aren't smart enough to resolve all symlinks
export PWD=$(pwd -P)

ARGS=""

DCKARGS="--privileged -v /dev:/dev --cap-add=SYS_ADMIN --cap-add SYS_PTRACE"
# Always pass X11
DCKARGS="${DCKARGS} -e DISPLAY -v ${HOME}/.Xauthority:/home/${WSUSER}/.Xauthority --net=host"

DAEMON=0

while [ $# -gt 0 ]; do
    first2=$(expr "$1" : '\(..\)')
    if [ "$first2" != "--" ]; then
        break
    fi

    case "$1" in
        --shell)
            ARGS="${ARGS} $1"
            DCKARGS="${DCKARGS} -it"
            shift
            ;;
        --super-shell)
            ARGS="${ARGS} $1"
            DCKARGS="${DCKARGS} -it"
            shift
            ;;
        --daemon)
            DCKARGS="${DCKARGS} -d"
            DAEMON=1
            shift
            ;;
	--directory)
	    cd $2
	    shift 2
	    ;;
    esac
done

# Use interactive -it flag on terminal
if [[ $DAEMON = 0 ]] ; then
    DCKARGS="${DCKARGS} --rm"
    # if [[ -t 1 ]] ; then
    #     DCKARGS="${DCKARGS} -it"
    # fi
fi

# if [ $# = 0 ] ; then
#     ARGS="${ARGS} --shell"
# fi

HOSTDIR="${PWD}"
DCKARGS=($DCKARGS)
ARGS=($ARGS)
IFS=
DCKARGS+=(-e)
DCKARGS+=(HOSTDIR="${HOSTDIR}")
docker run ${DCKARGS[@]} -v "${HOSTDIR}":"${APPDIR}" ${IMAGE} ${ARGS[@]} $@
STATUS=$?
exit ${STATUS}
